version: '3.3'
services:
    userservice:
        container_name: userservice
        image: userservice:v0.1.0

        networks:
            - red
        ports:
            - "9000:9000"
        env_file:
            - env_file
        restart: always
networks:
    red:
      external: true
