version: '3.3'
services:
    userservice:
        # container_name: userservice
        image: userservice:v0.6.0

        networks:
            - red
        # ports:
            # - "9000:9000"
        env_file:
            - .env
        restart: always

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.userservice.rule=Host(`${NAME}.localhost`)"
            - "traefik.http.services.userservice.loadbalancer.server.port=9000"
            - "traefik.http.routers.userservice.entrypoints=http,https,mysql,redis"
            - "traefik.http.routers.userservice.tls=true"

            #Configuracion Circuit Breaker
            - "traefik.http.middlewares.userservice-cb.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.30 || NetworkErrorRatio() > 0.10"

networks:   
    red:
      external: true
