version: '3.3'
services:
    userservice:
        image: userservice:v0.8.1
        networks:
            red:
                aliases:
                    - chat.chat.localhost
                    - user.chat.localhost
        env_file:
            - .env
        restart: always
        volumes:
        - ./_certs:/etc/certs:ro
        # deploy:
            # replicas: 2

networks:   
    red:
      external: true
