version: '3.3'
services:
    userservice:
        # container_name: userservice
        image: userservice:v0.4.0

        networks:
            - red
        # ports:
            # - "9000:9000"
        env_file:
            - .env
        restart: always

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.userservice.rule=Host(`${NAME}.localhost`)"
            - "traefik.http.services.userservice.loadbalancer.server.port=9000"
            # - "traefik.http.routers.chatservice.entrypoints=http,https,mysql"
            - "traefik.http.routers.userservice.tls=true"

networks:   
    red:
      external: true
