version: "3"

services:
  redis:
    image: redis:7.0.9
    restart: always
    volumes:
      - ./_data:/data
      - ./_data/redis.conf:/data/redis.conf
    command: redis-server /data/redis.conf #--requirepass ${REDIS_PASSWORD}
    ports:
      - "6378:6379"
    networks:
      - red

networks:
    red:
      external: true
      driver: bridge