http:
  routers:
    traefik:
      rule: "Host(`traefik.chat.localhost`)" #* 'chat' es el nombre de subdominio que se le asigna a la red
      service: "api@internal"
      tls:
        domains:
          - main: "chat.localhost"
            sans:
              - "*.chat.localhost"
          - main: "chat.local"
            sans:
              - "*.chat.local"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"