global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

  redis:
    address: ":6379"

  mysql:
    address: ":3306"

  # Agrega la entrada para WebSocket
  ws:
    address: ":7000"

  web:
    address: ":8000"

  websecure:
    address: ":8443"

http:
  # Agrega el middleware para WebSocket
  middlewares:
    websocket:
      headers:
        connectionUpgrade:
          value: "websocket"
        upgrade:
          value: "websocket"

  # Agrega la definición del router para WebSocket
  routers:
    websocket:
      entryPoints:
        - ws
      rule: "PathPrefix(`/ws`)"
      service: websocket-service
      middlewares:
        - websocket

  # Agrega la definición del servicio para WebSocket
  services:
    websocket-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "chat.chat.localhost"