version: '3.3'
services:
  chatservice:
    # container_name: chatservice
    image: chatservice:v0.7.1

    networks:
      red:
        aliases:
          - chat.chat.localhost
          - user.chat.localhost
    env_file:
      - .env
    restart: always
    volumes:
      - ./_certs:/etc/certs:ro
    #Configuracion Autoscaling de Traefik
    # deploy:
        # replicas: 2
networks:
  red:
    external: true
