version: '3.3'
services:
    chatservice:
        container_name: chatservice
        image: chatservice:v0.1.0

        networks:
            - red
        ports:
            - "7000:7000"
        env_file:
            - env_file
        restart: always
networks:
    red:
      external: true
