version: '3.3'
services:
  chatservice:
    # container_name: chatservice
    image: chatservice:v0.4.0

    networks:
      - red
    env_file:
      - .env
    restart: always

    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.chatservice.rule=Host(`${NAME}.localhost`)"
    - "traefik.http.routers.chatservice.tls=true"
    - "traefik.http.services.chatservice.loadbalancer.server.port=7000"
    # - "traefik.http.routers.chatservice.entrypoints=http,https,redis,mysql,web,websecure"
    - "traefik.http.services.chatservice.loadbalancer.sticky.cookie=true"
    - "traefik.http.services.chatservice.loadbalancer.sticky.cookie.name=mycookie"
    - "traefik.http.services.chatservice.loadbalancer.sticky.cookie.secure=true"

networks:
  red:
    external: true
