version: '3.3'
services:
    mysql:
        container_name: mysqlserver
        image: mysql:8.0-debian

        command: --default-authentication-plugin=mysql_native_password

        networks:
            - red
        ports:
            - "30000:3306"
        env_file:
            - env_file
        volumes:
            - ./_data:/var/lib/mysql
        # restart: always
networks:
    red:
      external: true
